services:
  postgres:
    image: postgres:15
    container_name: deb_besrat_pg
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: besrategebrel
      POSTGRES_PASSWORD: besrategebrel
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - odoo-db-data:/var/lib/postgresql/data/pgdata
    ports:
      - "5019:5432"
    restart: unless-stopped
    networks:
      - odoo-network

  odoo:
    image: odoo:18.0
    container_name: deb_besrat_web
    depends_on:
      - postgres
    ports:
      - "1900:8069"
      - "1019:8072"
    volumes:
      - odoo-web-data:/var/lib/odoo

      - ./etc/odoo.conf:/etc/odoo/odoo.conf
      - ./customs:/etc/odoo/customs
      - ./themes:/etc/odoo/themes
    environment:
      HOST: postgres
      USER: besrategebrel
      PASSWORD: besrategebrel
    restart: unless-stopped
    networks:
      - odoo-network
    user: "root:root"
    # install ibus ibus-m17n m17n-db
    command: [ "/bin/sh", "-c", "apt-get update && apt-get install -y ibus ibus-m17n m17n-db && /usr/bin/odoo --config=/etc/odoo/odoo.conf" ]

volumes:
  odoo-web-data:
  odoo-db-data:


networks:
  odoo-network:
    driver: bridge
